############################
## CHANGE THESE
############################

baseURL: "https://Peleke.github.io/swae-blog"
title: swae-blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
